name: Git Tool Runner
# Batch-ID: 1758460986364-0.22991162712449742
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone and Run Tool
        run: |
          git clone https://github.com/tbaolong193-cmd/tool2/blob/main/config.json
          cd tool
            node index.js
      - name: Keep Runner Alive
        run: sleep 21000