name: Git Tool Runner
# Batch-ID: 1758460698238-0.9715266499939685
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone and Run Tool
        run: |
          git clone https://github.com/teo8764678/tool.git
          cd tool
            node index.js
      - name: Keep Runner Alive
        run: sleep 21000