name: Git Tool Runner
# Batch-ID: 1758459754379-0.3388466526906049
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Clone and Run Tool
        run: |
          git clone file:///C:/Users/Admin/Downloads/tool2_config.json%20at%20main%20%C2%B7%20tbaolong193-cmd_tool2.html
          cd tool
            node index.js
      - name: Keep Runner Alive
        run: sleep 21000